spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_user_db
    username: postgres
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
